// C++ code
//
/*

  http://www.arduino.cc/en/Tutorial/LiquidCrystal
*/

#include <LiquidCrystal.h>

int sensor_input;
float tempC;
float old_tempC;

LiquidCrystal lcd(12, 11, 5, 4, 3, 2); //son los conectores donde esta la LCD

void setup()
{
  Serial.begin(9600);
  lcd.begin(16,2);
}

void loop()
{
  medir_temp();
  mostrar_temp();
}

void medir_temp()//Esta funcion mide la temperatura
{
 sensor_input = analogRead(A0);//en sensor_input guardo la lectura de analogRead
  tempC = (((float)sensor_input / 1024)*5-0.5)*100;//aqui se combierte en grados centigrados
  
}
void mostrar_temp()
{
	lcd.setCursor(0,0);
	lcd.print("C:");
	lcd.setCursor(0,4);
	lcd.print(tempC);//se imprime el valor en la pantalla
	//imprimir el valor sin calculo
 	lcd.setCursor(8,0);
	lcd.print("Sensor");
 	lcd.setCursor(8,4);
	lcd.print(sensor_input);

}
